Link to contents in wiki

diff --git a/simulate b/simulate
--- a/simulate
+++ b/simulate
@@ -19,9 +19,10 @@ function pm2() {
   node_modules/.bin/pm2 "$@"
 }
 
+# Clean up, stop all demoapps and nodes
 pm2 flush
 pm2 delete all || true
-killall Fairlayer 2>/dev/null || true
+killall node 2>/dev/null || true
 
 
 rm -rf data*
@@ -34,13 +35,10 @@ if node fs.js --genesis=test $db | grep "Genesis done"; then
     rsync -q -rva --exclude=offchain data/* data$i
   done
 
-
-
   pm2 start $pm2_opts --name wallet yarn -- parcel serve wallet -p $wallet_port
 
   fs_node_args="-p8433 --syncdb=off"
   pm2 start $pm2_opts --name fs fs.js -- $fs_cluster_args $fs_node_args
-  pm2 start $pm2_opts --name demoapp tools/demoapp.js
 
   for i in $(seq 8001 $maxport); do
     fs_node_args="-p$i --username=$i --pw=password --datadir=data$i"
@@ -51,6 +49,7 @@ if node fs.js --genesis=test $db | grep "Genesis done"; then
     fi
   done
 
+  pm2 start $pm2_opts --name demoapp tools/demoapp.js
 
   pm2 attach $(node -p "`pm2 id fs`[0]")  
 fi
